### PR TITLE
 ㅤ 

### PR DESCRIPTION
**Pull request by suprohub**

### CODE REVIEW

**Comment by suprohub** [comment]
what

**Comment by suprohub** [comment]
where the name

**Comment by suprohub** [comment]
github bruh

**Comment by tversteeg** [comment]
Thanks for the PR. What's the intended use for this? The code is currently not exposed in any way and gives a clippy warning that it's not used. Would you like text images to be able to split vertically instead of horizontally? Also, why is there a tiny image?

**Pull request closed without merging**
