### PR TITLE
feat(camera)!: add a main game and a UI camera system

### LINKED ISSUE #84: Camera
there the camera?

### PR DESCRIPTION
**Pull request by tversteeg**
Fixes #84.

Inspired by: https://github.com/a327ex/STALKER-X

TODO this PR:

- [x] Configuring lerp
- [ ] ~Configuring center in main game config~
- [ ] Dead zone
- [ ] Follow styles
- [ ] Follow lead

TODO later:

- [ ] Parallax scrolling
- [ ] Screen shake

@suprohub how do you feel about the API?

### CODE REVIEW

**Comment by suprohub** [comment]
error: process didn't exit successfully: `target\debug\examples\camera.exe` (exit code: 0xc000041d)

**Comment by suprohub** [comment]
0xC000041d its STATUS_FATAL_USER_CALLBACK_EXCEPTION

**Comment by suprohub** [comment]
no sprites - no error, draw sprites - error

**Comment by suprohub** [comment]
> @suprohub how do you feel about the API?
As for the API, I can say that by cameras I mean that there can be as many cameras as you like and you can switch between them, and somehow stretch them onto textures so that you can, for example, make a TV. Instead of the ui camera, I wanted to be able to set the speed of movement of an object for different cameras and the default speed of movement of an object in cameras. This way you can create parallax. The speed will be in a float from 1 (fully moving) to 0 (not moving, most likely this is ui).

**Comment by suprohub** [comment]
@tversteeg still crash error.

**Comment by tversteeg** [comment]
> @tversteeg still crash error.

Do you have a backtrace? Does it happen on all examples?

**Comment by suprohub** [comment]
> > @tversteeg still crash error.
> 
> Do you have a backtrace? Does it happen on all examples?

that's all there is (for some reason there is no backtrace)

C:/Users/superuser/.cargo/bin/cargo.exe run --color=always --package chuot --example camera
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.16s
     Running `target\debug\examples\camera.exe`
error: process didn't exit successfully: `target\debug\examples\camera.exe` (exit code: 0xc000041d)

Process finished with exit code -1073740771 (0xC000041D)

**Comment by suprohub** [comment]
shows a white screen for 5 seconds and crashes

**Comment by suprohub** [comment]
no all examples, some examples that crash: camera, render interp, sprite.
some examples that not crash: falling sand, audio.

**Comment by suprohub** [comment]
I think it has something to do with the main camera

**Comment by tversteeg** [comment]
That's very strange, I have no idea why there's no backtrace and also no idea what could possibly cause this.

**Comment by suprohub** [comment]
> That's very strange, I have no idea why there's no backtrace and also no idea what could possibly cause this.

what toolchain you use?

**Pull request merged**
